[project]
name = "crates-io-analysis"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=24.1.0",
    "aiohttp>=3.12.15",
    "asyncio>=4.0.0",
    "logging>=0.4.9.6",
    "requests>=2.32.5",
    "ruff>=0.13.1",
]
